### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by umbersar** [umbersar/sites_viz#5]
https://github.com/umbersar/sites_viz/blob/7d7e9413d9e2e1c4ea3459a95ddb884d2f76f359/app.R#L45

If i try to run this block of code, i get an error:
"Error in tag("div", list(...)) : argument is missing, with no default"

**Comment by ryan-di** [comment]
Do you mean that you were trying to run the code on its own?

**Comment by umbersar** [comment]
Yes. Was trying to run the code on its own. If that is not the suggested way to execute the app, please suggest how to run it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryan-di** [comment]
With the current structure of the app (having ui and server defined in the same script), you will have to click the "Run App" button on the top right. 


![image](https://user-images.githubusercontent.com/47294779/80566748-ff0b0200-8a36-11ea-82ba-b25eab1dc599.png)

**Comment by ryan-di** [comment]
With ui and server defined in separate files, one can run the app from the console. Maybe it's a good idea for me to create a document on shiny itself.

**Comment by umbersar** [comment]
Please document the steps required to run the app

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryan-di** [comment]
Will do.
