### ISSUE TITLE
Data table UI 

### ISSUE THREAD

**Issue by umbersar** [umbersar/sites_viz#6]
Column overflows to the right of the data grid (as seen in the attached snapshot). 

If the columns can't fit into the display area, try to use a scroll bar down below the grid.
 

![image](https://user-images.githubusercontent.com/11863217/81026766-87b5f200-8ebe-11ea-9145-5efed2af68af.png)

**Comment by umbersar** [comment]
Also, by default, display 10 entries in the data grid.

Also, make the size of the map down below the data grid a bit smaller. To test out what is the best size, try to reduce the size of map to 70% of what it currently is.

**Comment by ryan-di** [comment]
You're right. Adding a scroll bar would make more sense. 
Will try out different map sizes now that we're trying to piece things together. 

Thanks, Ramneek!
