### ISSUE TITLE
package ‘leafgl’ is not available (for R version 3.5.2)

### ISSUE THREAD

**Issue by umbersar** [umbersar/sites_viz#7]
I am running R version 3.5.2. When I try to install the package, I get this error:

> package ‘leafgl’ is not available (for R version 3.5.2)

Which R versions does leafgl support?

https://github.com/umbersar/sites_viz/blob/38ac99e219cf59a5f28a5988054b5d747b0750d0/app.R#L7

**Comment by ryan-di** [comment]
Please refer to the README file. At this stage, the package is only available via GitHub.

**Comment by umbersar** [comment]
Sure. Thanks.

It still does not install. Here is the error:

> > devtools::install_github("r-spatial/leafgl")
> Error: .onLoad failed in loadNamespace() for 'pkgload', details:
>   call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
>   error: there is no package called ‘backports’

I tested this by upgrading R to version 4.0.0
