### ISSUE TITLE
App crashes on loading a dataset

### ISSUE THREAD

**Issue by umbersar** [umbersar/sites_viz#8]
I tried to load h_texture morph attribute and the app crashed. I tested it with o_elevation attribute as well with same results.

![image](https://user-images.githubusercontent.com/11863217/82855718-67be9f00-9f4f-11ea-9129-34ab09f3c434.png)

**Comment by ryan-di** [comment]
I do not have this problem on my side and have never run into this problem before. 

Could you tell me how the error has occurred?

**Comment by ryan-di** [comment]
So it worked for all but these two particular datasets?

**Comment by umbersar** [comment]
No, it did not work for any of the datasets i tried.

I can reproduce the error by selecting a dataset and clicking on "Load
Dataset". See attached screenshot:

![image](https://user-images.githubusercontent.com/11863217/82859295-b2ddaf80-9f59-11ea-9021-a3c5876e604b.png)

**Comment by ryan-di** [comment]
I think I know what the problem is. Windows and UNIX (Linux) systems have different ways of denoting a file path. Will fix it now.

**Comment by ryan-di** [comment]
Just updated. Could you get the newest version and see if it works on your system?

**Comment by umbersar** [comment]
still gives me error:

![image](https://user-images.githubusercontent.com/11863217/82861867-6302e680-9f61-11ea-9af0-2214b4efea59.png)

**Comment by umbersar** [comment]
if u debug the code, error is being thrown in update_dt_data function in server.R (as is also suggested by error message)

**Comment by ryan-di** [comment]
Yeah I was gonna comment on that. Looks like it is not recognising the `-` sign in the `select` function. That's the `dplyr`'s way of dropping columns. 

I have now included the `dplyr::` in front of every `select` function. 

Code has been pushed. Let me know if it fixes the problem now.

Sorry about the back and forth.

**Comment by umbersar** [comment]
no luck. Same error.

**Comment by umbersar** [comment]
To test it, can u write that function in plain R without using dplyr. You can remove/select columns in dataframe without dplyr. 

try using subset function for dropping the columns

**Comment by ryan-di** [comment]
@umbersar I have now replaced the select(-) with native submitting. For the other uses of the select function, I have kept those for the sake of comparison. Please let me if the new code has fixed the problem. Let's get this fixed today.

**Comment by umbersar** [comment]
It worked fine with native subsetting. I guess we would have to replace them with native functionality.

**Comment by umbersar** [comment]
I tested with [h_texture] and [cf_shape] morph attributes and the "Load Dataset" functionality worked fine. But when i tried to load [lab_results], it threw an error:

![image](https://user-images.githubusercontent.com/11863217/82892228-75494880-9f92-11ea-80d6-9eae4ef2512d.png)

**Comment by ryan-di** [comment]
Here's some context:
In the initialisation phase, we divide the dataset into two data frames:
1. one with only data points whose geolocations are incomplete
2. one with only data points whose geolocations are complete

In all the morphology attributes datasets, the .csv files only had `NA` in geolocations. 
When other columns had missing values, it was denoted by "N/A". 

As such, in the code, I simply had:
```R
rv$geo_nas <- subset(data, c(o_longitude_GDA94, o_latitude_GDA94) %in% NA)
data <- na.omit(data)
# other initilisation with data
```

In `lab_results.csv`, however, we have `NA` in the spec_id column. 
This means that `data <- na.omit(data)` filters out the entire dataset.

`data <- na.omit(data)` is replaced by 
`data <- subset(data, (!c(o_longitude_GDA94, o_latitude_GDA94) %in% NA))`

We can work with `lab_results` now.

**Comment by umbersar** [comment]
i pulled the latest but [lab_results] still does not work on my end:

![image](https://user-images.githubusercontent.com/11863217/82959520-3f8c7a00-9ffb-11ea-88c9-a9c31eea17db.png)

**Comment by umbersar** [comment]
Here is the dump of stack trace and last error if that helps:

[stack_trace_sites.txt](https://github.com/umbersar/sites_viz/files/4685524/stack_trace_sites.txt)
[last_error_sites.txt](https://github.com/umbersar/sites_viz/files/4685525/last_error_sites.txt)

**Comment by ryan-di** [comment]
@umbersar I have now replaced all uses of the `select` function with native R code. Hope it works now.

**Comment by ryan-di** [comment]
@umbersar By the way, as noted in the README and Design Document, all the datasets that we provide must have the following three columns:
* `X`, which stores indexes, serves as an ID for each row
* `o_longitude_GDA94 `
* `o_latitude_GDA94 `

`NA` values are allowed in `o_longitude_GDA94` and `o_latitude_GDA94`. `NA` is not allowed in `X`.

**Comment by umbersar** [comment]
Did not work. This time it did load the data but the UI was greyed out. If it tried to click on page numbers in the data grid to see the next 10 entries, it threw this error:

![image](https://user-images.githubusercontent.com/11863217/82974841-3d87e280-a01e-11ea-970a-967235666947.png)

**Comment by umbersar** [comment]
I am mindful of your time and if you feel like you do not have much time left, don't feel pressured to fix the bug. You have done a good job overall.

**Comment by ryan-di** [comment]
@umbersar  why is Windows is so unfriendly 😂
I have not been able to reproduce the error. Datatable works fine on my end. 
![giphy](https://user-images.githubusercontent.com/47294779/82975788-c6a01900-a020-11ea-834f-0a5d9e756a2a.gif)

It works smoothly with the interactive map as well:
![giphy-1](https://user-images.githubusercontent.com/47294779/82975819-d9b2e900-a020-11ea-98b1-73feb0d602f5.gif)

I will investigate the problem after this week. Let me know if the problem persists.

**Comment by umbersar** [comment]
Datable works fine on my end for morphology attributes. That error was specifically for Lab_results datatable.

**Comment by umbersar** [comment]
I have dockerized the app and it runs fine including [Lab_results]. I will close the issue
